version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: amazon_db
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ..:/var/lib/postgresql/data
volumes:
  local_pgdata: